.github/workflows/node.js.yml
frontend/package-lock.json
frontend/package.json
frontend/src/components/Navbar.vue
frontend/src/style.css

Bump to v1.0.4

---

frontend/src/components/Navbar.vue
frontend/src/style.css

- navbar width was fixed by calculating max width based on the margin applied to both sides of the nav
- typo for theme toggle was fixed
- cursor will change to a pointer when hovering over links in the nav, it previously was not for the theme toggle
- some media queries were also removed as they weren't necessary
This is referencing issue #44

fix: width, cursor, and typo for navbar

---

frontend/src/components/Sidebar.vue
frontend/src/components/WonderfulPerson.vue
frontend/src/components/api/getGithubContributors.js
frontend/src/main.js
frontend/src/pages/ContributorsView.vue
frontend/src/router/router.js

With this page, we want to thank all contributors in a special way, hoping to continue improving more and more.
Added:
- faUsers icon
- router link for /contributors page
- github api to get contributors data
- contributors view

Added Contributors page

---

README.md

Follow up of #50 
+ Added links to **CODE_OF_CONDUCT.md and CONTRIBUTING.md**

Update README.md 2.0

---

frontend/src/components/Card.vue

- Changed height from 25vh to 100% to prevent overflow in the Card component. Resolves issue #54.

Update Card component height to fix overflow issue

---

frontend/src/components/Navbar.vue

This refer to issue #46 
Problem:
scrolling to the bottom doesn't go all the way down on navbar

fixed heigth on mobile screen to show all categories

---

frontend/src/style.css

modified card tags color

---

frontend/src/pages/Dashboard.vue

Issue belong #59 
video reference by adding code -
https://user-images.githubusercontent.com/66014487/235461335-3a30f673-9b5d-4167-807f-13c998e373c7.mp4

issue #59 subject to clearing card list when search input is not found.

---

frontend/src/components/Card.vue

This PR is for issue #84 
https://user-images.githubusercontent.com/19678157/235891162-a60d8f97-b349-4978-9b67-b6dab83904fb.mov
As you can see on the video, now the cards have a little effect on hover.
Let me know what you think about it

added scale transition

---

backend/data/entries.json

- SpamPatrol
- Official Carbon Intensity API
- Sumo-api

Added new submitted AP

---

backend/data/entries.json
backend/start.py

Fix for issue -> #89 
Now the correct number is back.

Fix #89 - Count API return wrong number

---

frontend/index.html

Optimize meta tag keywords to improve website SEO

updated meta keywords on index.html

---

frontend/src/components/Card.vue
frontend/src/pages/categories/[category].vue
frontend/src/style.css

Fixes #95 
- Changed the height of the Card to `100%`.
- Instead of  `row` added `grid`.
- Created reusable classes for `display: grid;` and `grid-template-columns: repeat(auto-fill, minmax(300px, 1fr));`

Fixed cards height Issue

---

frontend/package-lock.json
frontend/src/layouts/ContentBody.vue

@FlavioAdamo Please Check it I have changed the Margin top to 4vw

Changes the Margin top in content body file

---

frontend/src/layouts/ContentBody.vue

The api counter is now grey

---

frontend/src/layouts/ContentBody.vue

Issue from #114 - Prevent Horizontal scrolling in mobile version.
https://user-images.githubusercontent.com/66014487/236677269-e264dc98-5d7b-444a-b8ef-38c69471904c.mp4

Prevent Horizontal scrolling in mobile version. #114

---

frontend/src/components/Sidebar.vue
frontend/src/pages/Dashboard.vue
frontend/src/pages/categories/[category].vue

#104 - Cards and Repo link to open in a new tab
https://user-images.githubusercontent.com/94035734/236686830-c5085e58-2c2b-4b1a-a7fb-b50433c55a26.mp4

Cards and Repository links opens in a new tab

---

frontend/src/layouts/ContentBody.vue

Fixed trending title visibility on mobile

---

frontend/package-lock.json
frontend/src/components/Sidebar.vue

This change resolve #134 by adding the padding on a tag to fix the routing issues.

placed padding in a tag to fix routing issue

---

frontend/src/style.css

Is your feature request related to a problem? Please describe.
No, it is a modification to improve the user experience and text readability on the navbar in Dark mode.
Describe the solution you'd like
After conducting various tests, I believe that the best color for the text on the navbar is:
#e7e7e7
Unlike the original color, which is a bit darker, this color provides a more immediate reading of the various elements on the navbar.
#135 
@tarunsamanta2k20

enhancement-Make the text on the navbar lighter

---

frontend/src/components/TrendCategory.vue

Removed border from trending

---

frontend/src/components/Card.vue
frontend/src/components/CardAttributes.vue
frontend/src/components/FaviconCardApi.vue
frontend/src/components/LoadMoreButton.vue
frontend/src/components/TrendCategory.vue
frontend/src/layouts/ContentBody.vue
frontend/src/style.css

This PR contains the new card design.
Details are provided in the commit history.
-> #144

Issue 144 new card style -> #144

---

frontend/src/components/SearchBar.vue

https://github.com/Exifly/ApiVault/assets/16735648/a8e3a4c3-1391-43a8-9f2f-34b8cda5756c
#142

Added border gradient animation to search bar

---

frontend/src/components/Card.vue
frontend/src/components/TrendCategory.vue
frontend/src/style.css

Changed color of the searchbar to card background

---

frontend/src/components/LoadMoreButton.vue

removed border from load more button

---

frontend/src/components/LoadMoreButton.vue
frontend/src/components/LoadingEffectSmall.vue
frontend/src/pages/Dashboard.vue

Load spinner on load more (loading state)

---

frontend/src/components/Card.vue
frontend/src/components/LoadMoreButton.vue

Fix load more on mobile

---

frontend/src/components/Hero.vue
frontend/src/layouts/ContentBody.vue

Reduced padding and margins on homepage 
Fixes #149

Adjusted website to top

---

frontend/src/style.css

I opened the PR for issue #164.
I changed the hue of the color on hover.

fix: issue #164

---

frontend/components/CardAttributes.vue

#185 
Added `max-content` attribute to card badges

Not https text wrap on mobile devices fixed.

---

frontend/components/Sidebar.vue

Added highlighting for active category in sidebar
Closes #174 
Add styling to router-link-active class
[Include any additional information or context that may be helpful for reviewers.]

Added highlighting to active category

---

frontend/components/Hero.vue

This PR addresses a primarily known issue in production regarding the display of the subtitle on the homepage hero.
The **text-wrapper** class has been added to the *h5* tag. Additionally, unused code has been removed.

added text-wrapper class on h5 tag

---

frontend/components/SearchBar.vue

Text inside the search bar is fixed on mobile devices.

---

frontend/pages/categories/[category].vue

This PR Provide a little change on `[category].vue` page component.
With this modification, every time a user go to a category page, the html meta description will change based by category.
Added `meta` on `useHead` method in `[category].vue`.
```typescript
meta: [
{
name: "description",
content: `A List of your favourite ${route.params.category} APIs. For Free!`,
},
],
```

added dinamyc meta description

---

frontend/nuxt.config.ts
frontend/package.json
frontend/yarn.lock

Apivault has dynamic robots/sitemap generation now for better indexing on search engines.
The robots config is:
```typescript
export default [
{ UserAgent: '*' },
{ Disallow: '/' },
{ BlankLine: true },
{ Sitemap: () => 'https://apivault.dev/sitemap.xml' }
]
```
We are using the **simplest config** for now, preparing all dynamic routes inside `nuxt.config.ts`:
```typescript
sitemap: {
siteUrl: 'https://apivault.dev',
urls: async () => {
return categoriesProperties.map(category => ({
loc: `/categories/${category.name}`,
lastmod: new Date(),
changefreq: 'daily',
priority: 0.2,
}))
},
defaults: {
changefreq: 'daily',
priority: 0.5,
lastmod: new Date()
}
},
```
We should change this using `modules` in the future, when apivault will become bigger.

Fix/sitemap robots for SEO

---

frontend/nuxt.config.ts

Encoded `&` character in `sitemap.xml`

[Hot fix] v2.0.5

---

frontend/assets/styles/main.css
frontend/components/Navbar.vue
frontend/composables/theme.ts
frontend/nuxt.config.ts
frontend/pages/index.vue
frontend/utils/themeutils.ts

Refactored theme handler functions on `themeutils.ts` and `Navbar.vue` component.
Removed useless code logic and cleaned existent codebase.
With those changes, the theme handler is more efficient and stable using localStorage to store user theme preference.
In the future, we'd like to make sure to apply theme preference on website pre-rendering stage, to provide a powerful theme handler to users.
- Created a composable `useTheme` function to inject a `Ref` globally on the project:
```typescript
export const useTheme = () => {
return useState("APIVaultTheme", () =>
process.client ? localStorage.getItem("APIVaultTheme")! : "light"
)};
```
- Migrated the `setTheme()` function to `useTheme()` composable in `Navbar.vue` component:
```typescript
const theme = useTheme();
```
- Added …

refactoring and optimization for theme handler

---

backend/apivault/settings.py
backend/apivault/urls.py
backend/authentication/api.py
backend/authentication/google.py
backend/authentication/models.py
backend/authentication/register.py
backend/authentication/serializer.py
backend/authentication/urls.py
backend/interaction/models.py
backend/requirements.txt

Added google oauth for the new login system

FEATURE: Google authentication and Login system

---

frontend/pages/index.vue

The sponsor section in now hidden

hide spondor section

---

backend/vault/api.py

The search API will now return the correct 'liked_by_user' status

Fixed liked_by_user in search API

---

frontend/components/Navbar.vue

Fixed force reload on login function to sync all data correctly.

fixed force reload using router.go() function

---

frontend/components/SearchBar.vue
frontend/services/ApivaultServices.ts

As title said.
This add will fix the like state on APIs returned by Search API

fix/added accessToken on search API

---

frontend/components/Navbar.vue
frontend/components/user/Menu.vue
frontend/models/types.d.ts
frontend/services/ApivaultServices.ts

Added user information api.
fix:
- force update on logout

feat/added user information api on User component

---

frontend/components/Navbar.vue
frontend/components/Sidebar.vue
frontend/components/generics/Button.vue
frontend/components/generics/Modal.vue
frontend/components/user/Menu.vue
frontend/pages/user/apis.vue
frontend/services/ApivaultServices.ts

Added user apis page
- User pending APIs
- User approved APIs
Handled some check for authorization to submit an api. Minor bug fix.

Added user APIs page to manage user pending and added APIs:

---

frontend/assets/styles/main.css
frontend/components/generics/Toggle.vue

Changed border

---

backend/apivault/settings.py
backend/docker/command/start_server_prod.py

add static files

---

frontend/components/generics/Button.vue

Buttons on mobile were too large on mobile screen.

fixed button width broken on mobile screen

---

frontend/components/generics/ToastNotification.vue
frontend/pages/index.vue

This pr changes the standard notification with a toast one like this:
This is important for one reason in particular:
Users on mobile devices wouldn't have seen the notification message with the old design, but now it's visible 😄

changed notification to a toast notification

---

frontend/components/CardAPI.vue
frontend/components/Navbar.vue
frontend/components/Sidebar.vue
frontend/pages/index.vue

This pr fix a title issue on google search:

added title on index page meta tag + refactoring

---

frontend/error.vue

added custom error page

---

frontend/nuxt.config.ts

Modified title meta field to optimize google search rank

fixed title metadata field

---

frontend/components/ProductHuntBadge.vue
frontend/components/Sidebar.vue
frontend/package.json

Product hunt badge

---

.env.dev
backend/apivault/settings.py
backend/docker-compose.yml
docker-compose.dev.yml

Added support to control DEBUG flag value from env file.

Added support for controlling DEBUG flag from env

---

API_LIST.md

Hello, I added Softwium's fake API to Test data, and Pythonium's python check ter API to Programming.
Softwium's fake API to Test data (https://softwium.com/api/{resource})
Pythonium's python check ter API to Programming (https://pythonium.net/api/checker).

Add fake test data and python linter to API_LIST

---

frontend/.gitignore
frontend/.prettierrc
frontend/components/Footer.vue
frontend/components/Sidebar.vue
frontend/components/badges/CodeishotBadge.vue
frontend/nuxt.config.ts
frontend/package.json

In this PR, some improvements and additions have been made.
A new badge has been added, featuring one of our other apps, **Codeishot**, replacing the **ProductHunt** banner.
Additionally, a bug that made the page title of the **Contributors** section on Apivault invisible has been fixed.
Among the improvements, a `.prettierrc` file has been added to define formatting rules, and some files have already been formatted according to these new rules.
Finally, we've excluded Django's static files from the repository to prevent them from being included in future PRs.

Minor fixes and new badge added
